In [29]:
#importando a blibioteca pandas
import pandas as pd
pd.set_option('float_format', '{:.2f}'.format)

In [30]:
#importando os dados
df = pd.read_csv("Tabela investimento.csv", sep=';', encoding='utf-8')

df.head(13)

,Opção,Descrição,Custo do investimento (R$),Retorno esperado (R$),Risco do investimento (R$)
0,1,Ampliação da capacidade do armazém ZDP em 5%,470000,410000,Baixo
1,2,Ampliação da capacidade do armazém MGL em 7%,400000,330000,Baixo
2,3,Compra de empilhadeira,170000,140000,Médio
3,4,Projeto de P&D I,270000,250000,Médio
4,5,Projeto de P&D II,340000,320000,Médio
5,6,Aquisição de novos equipamentos,230000,320000,Médio
6,7,Capacitação de funcionários,50000,90000,Médio
7,8,Ampliação da estrutura de carga rodoviária,440000,190000,Alto
8,9,Construção de datacenter,320000,120000,Alto
9,10,Aquisição de empresa concorrente,800000,450000,Alto
10,11,Compra de serviços em nuvem,120000,80000,Baixo
11,12,Criação de aplicativo mobile e desktop,150000,120000,Baixo
12,13,Terceirizar serviço de otimização da logística,300000,380000,Médio

In [31]:
#colocando dados extras para teste
df.loc[len(df)] = ({"Opção":"14","Descrição":"Investimento novo","Custo do investimento (R$)":350000,"Retorno esperado (R$)":350000,"Risco do investimento (R$)":"Alto"})
df.loc[len(df)] = ({"Opção":"15","Descrição":"Investimento com Erro","Custo do investimento (R$)":-620000,"Retorno esperado (R$)":500000,"Risco do investimento (R$)":"Alto"})
df.loc[len(df)] = ({"Opção":"16","Descrição":"Investimento com risco diferente","Custo do investimento (R$)":250000,"Retorno esperado (R$)":350000,"Risco do investimento (R$)":"Muito Alto"})

In [32]:
#Aqui eu posso mudar minhas variaveis de acordo com a mudança cliente
capital_para_investimento = 2400000
num_min_investimento_medio = 2
num_min_investimento_alto = 1
num_min_investimento_baixo = 2
valor_max_investimento_medio = 1500000
valor_max_investimento_alto = 900000
valor_max_investimento_medio = 1200000

In [33]:
#Criando uma nova coluna para descobrir a porcentagem de ganho
df['Porcentagem de ganho (%)'] = df['Retorno esperado (R$)'] / df['Custo do investimento (R$)'] *100

In [34]:
#Criando mais uma coluna para ser o valor da porcentagem de ganho vezes o retorno esperado, criando assim a minha coluna base de melhores investimentos
df['Melhores Investimentos'] = df['Retorno esperado (R$)'] * df['Porcentagem de ganho (%)']
#Deixando a coluna em ordem de crescente em relação a coluna Melhores Investimentos
df = df.sort_values(by='Melhores Investimentos',ascending=False)
df

,Opção,Descrição,Custo do investimento (R$),Retorno esperado (R$),Risco do investimento (R$),Porcentagem de ganho (%),Melhores Investimentos
15,16,Investimento com risco diferente,250000,350000,Muito Alto,140.00,49000000.00
12,13,Terceirizar serviço de otimização da logística,300000,380000,Médio,126.67,48133333.33
5,6,Aquisição de novos equipamentos,230000,320000,Médio,139.13,44521739.13
0,1,Ampliação da capacidade do armazém ZDP em 5%,470000,410000,Baixo,87.23,35765957.45
13,14,Investimento novo,350000,350000,Alto,100.00,35000000.00
4,5,Projeto de P&D II,340000,320000,Médio,94.12,30117647.06
1,2,Ampliação da capacidade do armazém MGL em 7%,400000,330000,Baixo,82.50,27225000.00
9,10,Aquisição de empresa concorrente,800000,450000,Alto,56.25,25312500.00
3,4,Projeto de P&D I,270000,250000,Médio,92.59,23148148.15
6,7,Capacitação de funcionários,50000,90000,Médio,180.00,16200000.00
2,3,Compra de empilhadeira,170000,140000,Médio,82.35,11529411.76
11,12,Criação de aplicativo mobile e desktop,150000,120000,Baixo,80.00,9600000.00
7,8,Ampliação da estrutura de carga rodoviária,440000,190000,Alto,43.18,8204545.45
10,11,Compra de serviços em nuvem,120000,80000,Baixo,66.67,5333333.33
8,9,Construção de datacenter,320000,120000,Alto,37.50,4500000.00
14,15,Investimento com Erro,-620000,500000,Alto,-80.65,-40322580.65

In [35]:
#Aplicando uma limpeza no dataframe, deixando somente valores positivos e linhas com risco médio, baixo ou alto no dataframe
df = df[df['Melhores Investimentos'] >= 0]
filtro_medio = df[df['Risco do investimento (R$)'] == 'Médio']
filtro_baixo = df[df['Risco do investimento (R$)'] == 'Baixo']
filtro_alto = df[df['Risco do investimento (R$)'] == 'Alto']
df = pd.concat([filtro_baixo, filtro_medio, filtro_alto])


#Aplicando 3 filtros para pegar os melhores valores de cada
maiores_valores_medio = filtro_medio.nlargest(num_min_investimento_medio, 'Melhores Investimentos')
maiores_valores_baixo = filtro_baixo.nlargest(num_min_investimento_baixo, 'Melhores Investimentos')
maior_valor_alto = filtro_alto.nlargest(num_min_investimento_alto, 'Melhores Investimentos')

# Remover os valores obtidos do DataFrame original e juntar os valores obtidos em um dataframe
df = df.drop(maiores_valores_medio.index)
df = df.drop(maiores_valores_baixo.index)
df = df.drop(maior_valor_alto.index)
resultado = pd.concat([maiores_valores_medio, maiores_valores_baixo, maior_valor_alto])

#somando o valor total do custo de investimento que eu já tenho escolhido.
custo_total = resultado['Custo do investimento (R$)'].sum()

In [22]:
#Criando uma lista do meu dataframe com os 5 já escolhidos.
selecoes = [resultado.columns.tolist()] + resultado.values.tolist()

#Agora vou correr o dataframe linha por linha e se estiver dentro da condição ele vai adicionar a linha na minha lista
for _, row in df.iterrows():
    custo_investimento = row['Custo do investimento (R$)']
    # Checando se o custo total mais o custo do investivento da linha que está sendo lida é menor que 2400000
    if custo_total + custo_investimento <= capital_para_investimento:
      #agora o programa vai ver se o risco medio, alto e baixo já não passaram do valor máximo para cada categoria
        soma_risco_medio = sum(item[2] for item in selecoes if item[4] == 'Médio')
        soma_risco_alto = sum(item[2] for item in selecoes if item[4] == 'Alto')
        soma_risco_baixo = sum(item[2] for item in selecoes if item[4] == 'Baixo')
        if soma_risco_medio >= valor_max_investimento_medio:
            continue
        elif soma_risco_alto >= valor_max_investimento_alto:
            continue
        elif soma_risco_baixo >= valor_max_investimento_baixo:
            continue
        else:
            selecoes.append(row)
            custo_total += custo_investimento
    else:
        continue

# Criando um novo dataframe com a lista preenchida pelos investimentos.
df_selecoes = pd.DataFrame(selecoes[1:], columns=selecoes[0])
# colocando em ordem de melhor investimento e mostrando o valor total que será necessário investir.
df_selecoes = df_selecoes.sort_values(by='Melhores Investimentos',ascending=False)
display(df_selecoes)
Capital = df_selecoes['Custo do investimento (R$)'].sum()
print(f'Capital total investido: R$ {Capital}')

,Opção,Descrição,Custo do investimento (R$),Retorno esperado (R$),Risco do investimento (R$),Porcentagem de ganho (%),Melhores Investimentos
0,13,Terceirizar serviço de otimização da logística,300000,380000,Médio,126.67,48133333.33
1,6,Aquisição de novos equipamentos,230000,320000,Médio,139.13,44521739.13
2,1,Ampliação da capacidade do armazém ZDP em 5%,470000,410000,Baixo,87.23,35765957.45
3,2,Ampliação da capacidade do armazém MGL em 7%,400000,330000,Baixo,82.50,27225000.00
4,10,Aquisição de empresa concorrente,800000,450000,Alto,56.25,25312500.00
6,7,Capacitação de funcionários,50000,90000,Médio,180.00,16200000.00
5,12,Criação de aplicativo mobile e desktop,150000,120000,Baixo,80.00,9600000.00

Capital total investido: R$ 2400000

In [ ]:
df_selecoes.groupby('Risco do investimento (R$)')["Custo do investimento (R$)"].sum()

Risco do investimento (R$)
Alto      800000
Baixo    1020000
Médio     580000
Name: Custo do investimento (R$), dtype: int64